const places={
 tallinn:{name:'Tallinn · Tartu mnt',center:[59.4322,24.7649],base:68,count:27,victims:34,fatal:1,vulnerable:41,trend:'Õhtune tipptund',detail:'Kõige rohkem juhtumeid koondub tööpäeviti kell 16–19.',mode:'Jalakäijad',modeDetail:'Nõrgemate liiklejate osakaal on piirkonnas 41%.',change:'Risk on vähenenud',changeDetail:'Viimase kahe aasta näit on varasemast 12% madalam.'},
 tartu:{name:'Tartu · Riia / Ringtee',center:[58.3548,26.6948],base:61,count:19,victims:23,fatal:0,vulnerable:32,trend:'Hommikune tipptund',detail:'Juhtumeid koguneb enim kell 7–9 ja ristmike lähedusse.',mode:'Jalgratturid',modeDetail:'Iga viies kannatanu on olnud jalgrattur.',change:'Risk on püsinud',changeDetail:'Olulist muutust viimase kolme aasta jooksul ei paista.'},
 parnu:{name:'Pärnu · Tallinna mnt',center:[58.3924,24.5156],base:55,count:14,victims:17,fatal:1,vulnerable:36,trend:'Nädalavahetus',detail:'Suvekuudel kasvab juhtumite arv laupäeviti.',mode:'Jalakäijad',modeDetail:'Ülekäiguradade läheduses esineb selge koondumine.',change:'Hooajaline risk',changeDetail:'Juunist augustini on risk ülejäänud aastast kõrgem.'},
 kuressaare:{name:'Kuressaare · Tallinna tn',center:[58.2537,22.4894],base:37,count:7,victims:8,fatal:0,vulnerable:43,trend:'Pärastlõuna',detail:'Vähesed juhtumid koonduvad kell 14–17.',mode:'Jalgratturid',modeDetail:'Juhtumite arv on väike, kuid nõrgemate liiklejate osakaal kõrge.',change:'Madal juhtumitihedus',changeDetail:'Piirkond jääb näidisvõrdluses alla Eesti linnade keskmise.'}
};
let current='tallinn', uploadedData=null;
const map=L.map('map',{zoomControl:false}).setView(places[current].center,14);
L.control.zoom({position:'topright'}).addTo(map);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);
const layer=L.layerGroup().addTo(map); let radiusCircle;

function pseudoPoints(place,n){const pts=[];for(let i=0;i<n;i++){const a=(i*137.5)*Math.PI/180;const r=.002+((i*17)%13)/4000;pts.push({lat:place.center[0]+Math.sin(a)*r,lng:place.center[1]+Math.cos(a)*r*1.7,year:2023+(i%4),type:['auto','jalakäija','jalgrattur','auto','mootorratas'][i%5],severity:i%17===0?'hukkunu':'vigastus',victims:1+(i%4===0?1:0),hour:6+(i*7)%18});}return pts}
function withinRadius(p,c,km){const R=6371,dLat=(p.lat-c[0])*Math.PI/180,dLon=(p.lng-c[1])*Math.PI/180;const a=Math.sin(dLat/2)**2+Math.cos(c[0]*Math.PI/180)*Math.cos(p.lat*Math.PI/180)*Math.sin(dLon/2)**2;return R*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a))<=km}
function getData(){return uploadedData||pseudoPoints(places[current],places[current].count)}
function filtered(){const yf=document.querySelector('#yearFilter').value,tf=document.querySelector('#typeFilter').value,sf=document.querySelector('#severityFilter').value,rad=+document.querySelector('#radius').value,c=places[current].center;return getData().filter(p=>(yf==='all'||String(p.year)===yf)&&(tf==='all'||p.type===tf)&&(sf==='all'||p.severity===sf)&&withinRadius(p,c,rad))}
function render(){const p=places[current],data=filtered();layer.clearLayers();const rad=+document.querySelector('#radius').value;if(radiusCircle)map.removeLayer(radiusCircle);radiusCircle=L.circle(p.center,{radius:rad*1000,color:'#0d6b49',weight:1,fillColor:'#0d6b49',fillOpacity:.05}).addTo(map);data.forEach(d=>L.circleMarker([d.lat,d.lng],{radius:d.severity==='hukkunu'?8:6,color:'#fff',weight:2,fillColor:d.severity==='hukkunu'?'#e84b3c':'#ff8b52',fillOpacity:.9}).bindPopup(`<b>${d.severity==='hukkunu'?'Hukkunuga':'Vigastatuga'} õnnetus</b><br>${d.year} · ${d.type}<br>Kannatanuid: ${d.victims||1}`).addTo(layer));
 const fatal=data.filter(x=>x.severity==='hukkunu').length,victims=data.reduce((s,x)=>s+(x.victims||1),0),vul=data.length?Math.round(data.filter(x=>['jalakäija','jalgrattur'].includes(x.type)).length/data.length*100):0;let score=Math.min(96,Math.round(data.length*2.1+fatal*12+vul*.22));if(!uploadedData&&['all'].includes(document.querySelector('#yearFilter').value)&&document.querySelector('#typeFilter').value==='all'&&document.querySelector('#severityFilter').value==='all'&&rad===1.5)score=p.base;
 document.querySelector('#score').textContent=score;document.querySelector('#scoreBar').style.width=score+'%';document.querySelector('#scoreText').textContent=score>70?'Selles piirkonnas tasub olla tavapärasest tähelepanelikum, eriti tipptunnil.':score>45?'Piirkonnas esineb mõõdukas liiklusrisk, mis koondub kindlatesse aegadesse ja kohtadesse.':'Juhtumitihedus on valitud tingimustel pigem madal.';document.querySelector('.score-suffix span').textContent=score>70?'kõrge':score>45?'mõõdukas':'madal';
 document.querySelector('#areaTitle').textContent=p.name;document.querySelector('#accidentCount').textContent=data.length;document.querySelector('#victimCount').textContent=victims;document.querySelector('#fatalCount').textContent=fatal;document.querySelector('#vulnerableShare').textContent=vul+'%';
 document.querySelector('#insights').innerHTML=[[p.trend,p.detail,'◷'],[p.mode,p.modeDetail,'♙'],[p.change,p.changeDetail,'↘']].map(x=>`<div class="insight"><span class="insight-icon">${x[2]}</span><div><b>${x[0]}</b><p>${x[1]}</p></div></div>`).join('');renderBars(data);}
function renderBars(data){const bins=Array(12).fill(0);data.forEach(d=>bins[Math.min(11,Math.floor((d.hour||12)/2))]++);const max=Math.max(1,...bins);document.querySelector('#bars').innerHTML=bins.map((v,i)=>`<div class="bar-col"><div class="bar ${v===max?'peak':''}" style="--h:${Math.max(4,v/max*150)}px" title="${v} juhtumit"></div>${String(i*2).padStart(2,'0')}</div>`).join('')}
function detect(row,names){const key=Object.keys(row).find(k=>names.some(n=>k.toLowerCase().includes(n)));return key?row[key]:undefined}
function parseCSV(text){const sep=(text.split('\n')[0].match(/;/g)||[]).length>(text.split('\n')[0].match(/,/g)||[]).length?';':',';const lines=text.trim().split(/\r?\n/),heads=lines[0].split(sep).map(s=>s.replace(/^"|"$/g,'').trim());return lines.slice(1).map(line=>{const vals=line.split(sep).map(s=>s.replace(/^"|"$/g,'').trim()),r=Object.fromEntries(heads.map((h,i)=>[h,vals[i]]));const lat=Number(String(detect(r,['latitude','lat','y koord','y_koord'])).replace(',','.')),lng=Number(String(detect(r,['longitude','lon','lng','x koord','x_koord'])).replace(',','.'));if(!Number.isFinite(lat)||!Number.isFinite(lng))return null;const date=detect(r,['kuupäev','kuupaev','date','toimumisaeg'])||'';const desc=Object.values(r).join(' ').toLowerCase();return{lat,lng,year:Number(String(date).match(/20\d{2}/)?.[0]||2026),type:desc.includes('jalakä')?'jalakäija':desc.includes('jalgr')?'jalgrattur':desc.includes('mootorr')?'mootorratas':'auto',severity:desc.includes('hukk')?'hukkunu':'vigastus',victims:Number(detect(r,['kannatan','vigastat'])||1),hour:Number(String(date).match(/\b([01]?\d|2[0-3]):/)?.[1]||12)}}).filter(Boolean)}

document.querySelector('#analyseBtn').onclick=()=>{current=document.querySelector('#placeSelect').value;uploadedData=null;map.setView(places[current].center,14);render()};['yearFilter','typeFilter','severityFilter','radius'].forEach(id=>document.querySelector('#'+id).oninput=()=>{document.querySelector('#radiusValue').textContent=String(document.querySelector('#radius').value).replace('.',',')+' km';render()});document.querySelector('#resetBtn').onclick=()=>{document.querySelector('#yearFilter').value='all';document.querySelector('#typeFilter').value='all';document.querySelector('#severityFilter').value='all';document.querySelector('#radius').value=1.5;document.querySelector('#radiusValue').textContent='1,5 km';render()};document.querySelector('#uploadBtn').onclick=()=>document.querySelector('#csvInput').click();document.querySelector('#csvInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{uploadedData=parseCSV(reader.result);if(!uploadedData.length){alert('Koordinaatidega ridu ei leitud. Kontrolli CSV veerunimesid.');uploadedData=null;return}const avg=[uploadedData.reduce((s,x)=>s+x.lat,0)/uploadedData.length,uploadedData.reduce((s,x)=>s+x.lng,0)/uploadedData.length];places[current].center=avg;map.setView(avg,13);render();alert(`Laaditud ${uploadedData.length} koordinaatidega kirjet.`)};reader.readAsText(f,'utf-8')};const dlg=document.querySelector('#methodDialog');document.querySelector('#methodBtn').onclick=()=>dlg.showModal();dlg.querySelector('.close').onclick=()=>dlg.close();render();
